version: '3'
services:
  app:
    container_name: docker-express-mongo
    restart: always
    build: .
    ports:
      - '9000:9000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'